name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * # 8 am IST
    - cron: 00 14 * * * # 7:30 pm IST
    - cron: 00 06 * * 1-5 # 11:30 am IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Newman and HtmlExtra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection with Newman
        run: |
          mkdir -p newman   # ✅ ensures folder exists
          newman run "Inwarranty-flow collection.postman_collection.json" \
            -e QA.postman_environment.json \
            -d testdata.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman/index.html
          ls -R newman      # ✅ verify file existence (debugging)

      - name: Upload Newman HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman/index.html   # ✅ exact file path
          if-no-files-found: error  # fail if missing

      - name: Publish to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
          
      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME}}
          password: ${{ secrets.EMAIL_PASSWORD}}
          subject: Phoenix Inwarranty Flow Test Execution Notification
          to: pooja.deevi19@gmail.com
          from: ${{ secrets.EMAIL_USERNAME}}
          body: 
                Hi,
                Phoenix inwarranty flow tests has been executed.The report has been published and the url 
                is:https://poojadeevi19.github.io/Phoenix-Inwarranty-Flow/
                 
          
          
